### ISSUE TITLE
object instances as arguments to memoize() decorated function

### ISSUE THREAD

**Issue by alanhamlett** [thadeusb/flask-cache#36]
When passing an object instance as an argument to a function decorated with memoize, the cache key is calculated from calling id() on that function. Python's id() only returns a unique id for the lifetime of that object. The lifetime of an object is 1 request when in the Flask request context.

**Comment by alanhamlett** [comment]
For background from outside discussion:

http://packages.python.org/Flask-Cache/#memoization

The docs say memoize() takes into account an instance's id, however
i'm having key collisions when passing a function wrapped in
cache.memoize() an SqlAlchemy db model. Are the docs not talking about
a database instance object? The generate key function never looks at
an argument's id.

**Comment by thadeusb** [comment]
I got the docs terribly wrong, and found a bug when updating them.

The intent is that a method of a class can me memoized as well as regular functions. However, since there can be multiple instances of a class, the id() of the class has to be considered as part of a methods cache_key.

As far as passing in instances as arguments, currently it just converts all arguments to strings with string formatting, and we need to discuss if it should be left up to the programmer to determine a unique representation of an object or if id() or hash() should be called on objects.

I feel that it should be left up to the programmer.

A magic `__cacherepr__` function could be added to an object, and flask_cache could use this instead of repr(obj) if it is defined. The only opinion I have on this is that it adds one more thing to check for when building a cache key.

**Comment by thadeusb** [comment]
Changes for this will be made in the [memoized_instancemethod branch](https://github.com/thadeusb/flask-cache/compare/memoized_instancemethod)

New proposed documentation

---

In memoization, the functions arguments are also included into the cache_key.

.. note::

```
With functions that do not receive arguments, :meth:`~Cache.cached` and
:meth:`~Cache.memoize` are effectively the same.
```

Memoize is also designed for methods, since it will take into account
the `identity <http://docs.python.org/library/functions.html#id>`_. of the
'self' or 'cls' argument as part of the cache key.

The theory behind memoization is that if you have a function you need
to call several times in one request, it would only be calculated the first
time that function is called with those arguments. For example, an sqlalchemy
object that determines if a user has a role. You might need to call this
function many times during a single request. To keep from hitting the database
every time this information is needed you might do something like the following::

```
class Person(db.Model):
    @cache.memoize(50)
    def has_membership(self, role_id):
        return Group.query.filter_by(user=self, role_id=role_id).count() >= 1
```

.. warning::

```
Using mutable objects (classes, etc) as part of the cache key can become
tricky. It is suggested to not pass in an object instance into a memoized
function. However, the memoize does perform a repr() on the passed in arguments
so that if the object has a __repr__ function that returns a uniquely
identifying string for that object, that will be used as part of the
cache key.

For example, an sqlalchemy person object that returns the database id as
part of the unique identifier.::

class Person(db.Model):
    def __repr__(self):
        return "%s(%s)" % (self.__class__.__name__, self.id)
```

**Comment by alanhamlett** [comment]
I agree with using the string representation of a class instance as part of the cache key. The programmer should implement `__repr__`, and a flask-cache specific `__cacherepr__` isn't needed.

I just read over your changes and everything looks good!
