### ISSUE TITLE
Memoize does not respect the parameter timeout

### ISSUE THREAD

**Issue by teleyinex** [thadeusb/flask-cache#78]
Hi,

I'm having problems with the timeout parameter for the memoize decorator. It looks like it is never respected, putting in the cache always the default timeout: 300 (unless you modify it in the config file). Interestingly, with cached it works as expected.

I'm using it like this:

@cache.memoize(timeout=999)
def foo(arg1, arg2):
    pass

I'm using REDIS as the backend, any ideas?

**Comment by jimmyngo** [comment]
I ran into this problem as well. It looks like this is due to the internal versioning that is being used. 

Within make_cache_key:

```
        version_key = self._memvname(fname)
        version_data = self.cache.get(version_key)

        if version_data is None:
            version_data = self.memoize_make_version_hash()
            self.cache.set(version_key, version_data)
```

There is no timeout being set for the version_key so it falls to the default timeout. At which point, the internal version number used to calculate the cache_key changes. Seems like the timeout parameter needs to be passed in to the set, but I feel like the value of version_key should never change unless it is explicitly deleted.

**Comment by teleyinex** [comment]
At the end I created my own library for the cache using only Redis and its Sentinel mode for having a high availability and load balanced cache within several nodes :-) I agree with you on the explanation, so a fix should be easy.

**Comment by thadeusb** [comment]
fixed
